spring:
  application:
    name: spring_mcp
  main:
    web-application-type: servlet
    banner-mode: off
  ai:
    mcp:
      server:
        name: kmakker-mcp-server
        version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my_schema
    username: postgres
    password: PostgresXXXX
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
server:
    port: 8081