spring:
  application:
    name: spring_mcp
  main:
    web-application-type: reactive
    banner-mode: off
  ai:
    mcp:
      server:
        name: kmakker-mcp-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-message-endpoint: /mcp/message
        sse-endpoint: /api/v1/sse


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my_schema
    username: postgres
    password: PostgresXXXX
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console:
server:
    port: 8085